include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_fields: true
    use_build_context_synchronously: true

